replicaCount: 3
image:
  repository: sergiogg06/portafolioreact  # Cambiado para que coincida con tu Docker Hub
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: NodePort
  port: 80
  nodePort: 30081
ingress:
  host: sergiogallardogrima.com
  wwwHost: www.sergiogallardogrima.com
  clusterIssuer: letsencrypt-prod