replicaCount: 3
image:
  repository: sergiogg06/portafolioreact
  tag: "latest"
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  nodePort: 30081
ingress:
  host: sergiogallardogrima.com
  wwwHost: www.sergiogallardogrima.com
  clusterIssuer: letsencrypt-prod