apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-react-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sergioga06/portafolioreact.git' # Tu repo real
    targetRevision: HEAD
    path: deploy/miportfolio # Ruta donde está el Chart.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: proyectoportfolio # El namespace de tu app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true