apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: portfolio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    spec:
      containers:
        - name: portfolio
          image: sergiogg06/portafolioreact:latest # Asegúrate de haber subido la imagen a Docker Hub
          ports:
            - containerPort: 80