apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  # SE ELIMINA: namespace: miportfolio
spec:
  type: {{ .Values.service.type }}
  selector:
    app: portfolio
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}